// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMQUalvHh-Z3LxP2nScO4B2MG2_NnnNO0',
    appId: '1:252829411873:web:a4f1cb8ff179fc32c6d160',
    messagingSenderId: '252829411873',
    projectId: 'gobinew',
    authDomain: 'gobinew.firebaseapp.com',
    storageBucket: 'gobinew.firebasestorage.app',
    measurementId: 'G-FZ69ZF6GE0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsuJj2TEcoxIDOWRKoF2LvRG9FpGoXWXY',
    appId: '1:252829411873:android:21fe65d69dabb426c6d160',
    messagingSenderId: '252829411873',
    projectId: 'gobinew',
    storageBucket: 'gobinew.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDplNenK9-RSe-6j71sz317HgAsMnKcrY0',
    appId: '1:252829411873:ios:b5d4c17fa904aedfc6d160',
    messagingSenderId: '252829411873',
    projectId: 'gobinew',
    storageBucket: 'gobinew.firebasestorage.app',
    androidClientId: '252829411873-k8f56b2ssn53jejuh7bvhlbsrmar8f1m.apps.googleusercontent.com',
    iosClientId: '252829411873-p3nc6pi7snufqqt2l6cdol587kjlak3n.apps.googleusercontent.com',
    iosBundleId: 'com.gobi.gobinew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMQUalvHh-Z3LxP2nScO4B2MG2_NnnNO0',
    appId: '1:252829411873:web:4b241593bfef3f5fc6d160',
    messagingSenderId: '252829411873',
    projectId: 'gobinew',
    authDomain: 'gobinew.firebaseapp.com',
    storageBucket: 'gobinew.firebasestorage.app',
    measurementId: 'G-QQNLBCYD0E',
  );
}
